# Generated by Django 5.0.4 on 2024-06-21 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='momdaughters',
            name='image',
            field=models.ImageField(upload_to='static/media/'),
        ),
    ]
